version: "3.9"
services:
    api:
        image: "borobongo/docker-northwind-api"
        build: .
        ports: 
        - "8080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports: 
        - "1433:1433"
        volumes:
        - "./init.sql:/data/application/init.sql"
        environment:
            SA_PASSWORD: "Passw0rd12"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express