apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000 # 30000-32767, Optional field